Add missing method to get all datasources
grafana-cold-storage/grafana-api-golang-client pull request #12
Opened 2020-10-21 07:47 UTC by akamensky

2020-10-21 07:50 UTC, aknuds1 requested changes, later dismissed
Have to check if this is something we want, but saw some things that should be fixed.

2020-10-21 07:50 UTC, aknuds1 commented on datasource.go
> +	return result, err
```suggestion
	return result, nil
```

2020-10-21 07:50 UTC, aknuds1 commented on datasource.go
> +// DataSources returns all data sources as defined in Grafana
```suggestion
// DataSources returns all data sources as defined in Grafana.
```

2020-10-21 08:07 UTC, akamensky commented
FWIW other than period at the end of the sentence the rest was just copy/paste from code right above it...

2020-10-21 08:09 UTC, akamensky commented
> Have to check if this is something we want, but saw some things that should be fixed.

I mean, you have methods to create/delete/update datasources, but no method to get their list??? I am using my own fork vendored in, just because your CRUD interface is not complete.

2020-10-21 08:11 UTC, aknuds1 commented
> FWIW other than period at the end of the sentence the rest was just copy/paste from code right above it...

That doesn't mean we shouldn't make improvements.

2020-10-22 02:14 UTC, akamensky commented
@aknuds1 please review the changes as your requested.

2020-10-22 05:26 UTC, aknuds1 commented
I already said we need to discuss internally before deciding:

> Have to check if this is something we want

Please have some patience.

2020-10-22 05:39 UTC, akamensky commented
> I already said we need to discuss internally before deciding:
> 
> Please have some patience.

I am asking to review the changes you yourself requested, not the merging and of the changes. Do take your time with discussion if that's the policy. And no need to be rude about it.

2020-10-22 06:03 UTC, aknuds1 commented
I'm not being rude, far from it. We will get back to you when we've had the time to review the feature addition.

2020-10-27 00:23 UTC, jinjaghost commented
@akamensky: what do you think of adding the custom header "x-grafana-org-id" to make this method capable of listing datasources for a given OrgId ? This is the way the grafana backend knows the current orgId.

2020-10-27 02:05 UTC, akamensky commented
@jinjaghost that would be inconsistent with other queries in this library. And also that should be it's own method in library as it won't be fetching all data sources, but their subset. Something named like "GetDataSourcesByOrgId".

2020-11-18 14:54 UTC, aknuds1 reviewed
We've discussed it and decided that even though the client is in deprecated mode now, we can accept the PR. Are you able to add a test though?

2021-12-14 06:07 UTC, Etherdaemon commented
> We've discussed it and decided that even though the client is in deprecated mode now, we can accept the PR. Are you able to add a test though?

Hi @aknuds1 - when you say this client is in deprecated mode, what is the alternative client to be used with terraform-provider-grafana? I was planning on putting a bit of work into adding the new alert v2 parts from Grafana v8.3.X

2022-05-28 22:41 UTC, davidnewhall commented
This doesn't really seem deprecated?

2022-06-15 17:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana-api-golang-client?pullRequest=12) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana-api-golang-client?pullRequest=12) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana-api-golang-client?pullRequest=12) it.</sub>

2022-08-10 22:15 UTC, jalevin commented
I believe this is now taken care of. https://github.com/grafana/grafana-api-golang-client/blob/9c38b6f437bb9688f655ace9e66cc8b8f91ce0f4/datasource.go#L371

2022-08-10 22:15 UTC, closed without merging